version: 0.0
os: linux
files:
- source: /
  destination: /tmp/aviatorsbot-scala-deploy
hooks:
  BeforeInstall:
  - location: scripts/before_install.sh
    timeout: 60
    runas: root
  AfterInstall:
  - location: scripts/install_package.sh
    timeout: 300
    runas: root