version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Run the test and package the code...
      - sbt compile
      - sbt test
  post_build:
    commands:
      - echo Build completed on `date`
      - sbt debian:packageBin
artifacts:
  files:
    - target/scala-2.12/aviatorsbot-scala-1.0.deb