{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aviatorsbot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aviatorsbot.name" . }}
    helm.sh/chart: {{ include "aviatorsbot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aviatorsbot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
